### PR TITLE
Update DAORayaki Bounty 2021-12-27

### PR DESCRIPTION
**Pull request by Brindrajsinh-Chauhan**
Translation for Optimistic Roll-ups: the Present and future of Ethereum scaling

### CODE REVIEW

**Comment by Will-Holden** [comment]
Hi Brindrajsinh-Chauhan, please make sure that u hackerlink account is bounded with your address. Otherwise it may cause a failed when claim your bounty.

**Comment by depth-first** [comment]
Please test if [my solution](https://github.com/DAOrayaki/DAOrayaki-Bounty/issues/21#issuecomment-1003512588) works.

**Comment by Will-Holden** [comment]
Hi Brindrajsinh-Chauhan, please make sure this account can access u doc daorayaki@dorafactory.org

**Comment by Will-Holden** [comment]
非常感谢您的参与，本次参与未通过的原因，请前往提交文档查看。

**Pull request closed without merging**
