### PR TITLE
#33 Update DAORayaki Bounty | SpaceTEE: Secure and Tamper-Proof Computing in Space using CubeSats

### PR DESCRIPTION
**Pull request by tw23**
#33

### CODE REVIEW

**Comment by Will-Holden** [comment]
hellow tw23, U share doc links is not on the record files, please add that

**Comment by tw23** [comment]
Thanks for your reminder. I will share doc links on GitHub soon. The
translation will be finished about tomorrow.


will ***@***.***>於 2022年1月22日 週六，下午3:13寫道：

**Comment by Will-Holden** [comment]
Hellow, please submit u share doc links on the record files.

**Comment by tw23** [comment]
> Hellow, please submit u share doc links on the record files.
https://docs.google.com/document/d/1E5KqAIVKqV0obBK-UOcUnQ31jhuyof-ZJ7J8GS43FaA/edit?usp=sharing

**Pull request merged**
